# Generated by Django 4.2.3 on 2023-11-02 07:18

from django.db import migrations, models
import sampler_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HazardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chemical_hazards', 'Chemical Hazards'), ('biological_hazards', 'Biological Hazards'), ('radiological_hazards', 'Radiological Hazards'), ('physical_hazards', 'Physical Hazards'), ('fire_and_explosion_hazards', 'Fire and Explosion Hazards'), ('ergonomic_hazards', 'Ergonomic Hazards'), ('noise_hazards', 'Noise Hazards'), ('environmental_hazards', 'Environmental Hazards'), ('biological_safety_level', 'Biological Safety Level'), ('physical_security_hazards', 'Physical Security Hazards')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('staff', 'Staff'), ('student', 'Student')], max_length=20)),
                ('user_name', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
                ('sample_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('unique_code', models.CharField(default=sampler_app.models.generate_unique_code, editable=False, max_length=5, unique=True)),
                ('hazard', models.ManyToManyField(blank=True, to='sampler_app.hazardtype')),
            ],
        ),
    ]
