# Generated by Django 4.2.3 on 2023-10-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=10)),
                ('sample_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('hazard_type', models.CharField(max_length=50)),
                ('submission_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('unique_code', models.CharField(max_length=5, unique=True)),
            ],
        ),
    ]
