# Generated by Django 4.2.3 on 2023-10-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampler_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='sample',
            name='hazard_type',
        ),
        migrations.AlterField(
            model_name='sample',
            name='submission_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='sample',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='sample',
            name='user_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('student', 'Student')], max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='user_name',
            field=models.ManyToManyField(to='sampler_app.username'),
        ),
        migrations.AddField(
            model_name='sample',
            name='hazard_type',
            field=models.ManyToManyField(to='sampler_app.hazardtype'),
        ),
        migrations.AddField(
            model_name='sample',
            name='user_id',
            field=models.ManyToManyField(to='sampler_app.userid'),
        ),
    ]
