# Generated by Django 4.2.3 on 2023-10-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampler_app', '0003_alter_hazardtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='unique_code',
            field=models.CharField(default='', max_length=5, unique=True),
        ),
    ]
